version: 0.0
os: windows
files:
  - source: /
    destination: /tmp/code-deploy.skeleton
hooks:
  ApplicationStop:
    - location: code-deploy/application-stop.ps1
      runas: root
  BeforeInstall:
    - location: code-deploy/before-install.ps1
      runas: root
  AfterInstall:
    - location: code-deploy/on-after-install.ps1
      runas: root
  ApplicationStart:
    - location: code-deploy/application-start.ps1
      runas: root
  ValidateService:
    - location: code-deploy/validate-service.ps1
      runas: root